### PR TITLE
supporting onComplete and onFailure

### PR DESCRIPTION
**Pull request by ffissore**
#10 has been closed without being merged. Opening a new one since we use this feature in our ember app

### CODE REVIEW

**Comment by rynam0** [comment]
So sorry about #10.  I truly had the intention of writing some tests for this and merging but it slipped my mind due to other things cropping up at work.  If you could supply some simple test coverage I'll get this merged in ASAP.  Again, my apologies.

**Comment by ffissore** [comment]
I've added a test for `onComplete`. I don't know how to make swagger-ui fail so to check for `onFailure` as well

**Comment by rynam0** [comment]
Thanks!

**Comment by rynam0** [comment]
This is in 0.0.20 now.  Thanks again and sorry about missing the previous contribution.

**Pull request merged**
