### PR TITLE
Upgrade to swagger-ui 2.2.6

### PR DESCRIPTION
**Pull request by TheAxeMan301**
How about moving to the latest version of swagger?

### CODE REVIEW

**Comment by TheAxeMan301** [comment]
Hmm, the dummy app loads up fine. Not sure how to troubleshoot the other issues.

**Comment by rynam0** [comment]
Thanks!

**Comment by TheAxeMan301** [comment]
Thank you!

**Comment by TheAxeMan301** [comment]
Thanks @rynam0!

**Pull request merged**
