### PR TITLE
Add ability to set any swagger option

### PR DESCRIPTION
**Pull request by TheAxeMan301**
@rynam0 Got things working by not using lodash. Wait a bit though, I will add some more tests.

### CODE REVIEW

**Comment by TheAxeMan301** [comment]
This is running for me on Chrome but not PhantomJS. I would recommend discontinuing PhantomJS as it isn't really relevant anymore. Thanks for checking out these changes @rynam0!

**Comment by rynam0** [comment]
@TheAxeMan301: sorry for the delay on this but what is the issue you are seeing when running tests on PhantomJS?

**Comment by TheAxeMan301** [comment]
@rynam0 You can see on the earlier builds. Anyway, I am no longer working with EmberJS so I won't be making any more contributions. Sorry.

**Comment by rynam0** [comment]
Oh, alright. Thanks for everything you've done here 😀

**Comment by rynam0** [comment]
Closing in favor of #44

**Pull request closed without merging**
